import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    return localizations ?? AppLocalizations(const Locale('en'));
  }

  String t(String key) {
    final lang = locale.languageCode;
    return _localizedValues[lang]?[key] ?? _localizedValues['en']![key]!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcomeBack': 'Welcome back',
      'signInSubtitle': 'Sign in to continue building your Digital CV.',
      'loginFailed': 'Login failed. Please check your credentials.',
      'invalidEmail': 'Enter a valid email address.',
      'userNotFound': 'No account found with this email.',
      'wrongPassword': 'Incorrect password. Try again.',
      'userDisabled': 'This account has been disabled.',
      'operationNotAllowed': 'Email/password sign-in is disabled.',
      'tooManyRequests': 'Too many attempts. Try again later.',
      'email': 'Email',
      'password': 'Password',
      'rememberMe': 'Remember me',
      'rememberMeHint': 'Stay signed in on this device.',
      'forgotPassword': 'Forgot password?',
      'signIn': 'Sign in',
      'signingIn': 'Signing in...',
      'googleConnecting': 'Connecting to Google...',
      'continueWithGoogle': 'Continue with Google',
      'googleCanceled': 'Google sign-in was canceled.',
      'googleFailed': 'Google sign-in failed. Please try again.',
      'googleShaHint':
          'Google sign-in failed. Add SHA-1/256 in Firebase and try again.',
      'networkError': 'Network error. Check your connection and try again.',
      'newToDigitalCv': 'New to Digital CV?',
      'createAccount': 'Create account',
      'creatingAccount': 'Creating account...',
      'createAccountTitle': 'Create your account',
      'createAccountSubtitle': 'Build a premium CV in minutes.',
      'fullName': 'Full name',
      'registrationFailed': 'Registration failed. Try a different email.',
      'useAtLeast6': 'Use at least 6 characters.',
      'nameRequired': 'Name is required.',
      'emailRequired': 'Email is required.',
      'passwordRequired': 'Password is required.',
      'resetPasswordTitle': 'Reset password',
      'resetPasswordSubtitle': 'We will email you a secure reset link.',
      'resetLinkSent': 'Reset link sent. Check your inbox.',
      'resetFailed': 'Unable to send reset link. Try again.',
      'sendResetLink': 'Send reset link',
      'sending': 'Sending...',
      'editCv': 'Edit CV',
      'editCvSubtitle': 'Update your personal data and sections',
      'previewCv': 'Preview CV',
      'previewCvSubtitle': 'See the current template',
      'changeTemplate': 'Change Template',
      'changeTemplateSubtitle': 'Modern or Classic styles',
      'exportPdf': 'Export PDF',
      'exportPdfSubtitle': 'Generate a professional PDF',
      'logout': 'Logout',
      'logoutSubtitle': 'Sign out from your account',
      'dashboard': 'Dashboard',
      'cvCompletion': 'CV completion',
      'actions': 'Actions',
      'settings': 'Settings',
      'theme': 'Theme',
      'darkModeNote':
          'Dark mode is enabled by default for a premium, consistent look.',
      'profileDetails': 'Profile details',
      'phoneNumber': 'Phone number',
      'locations': 'Locations',
      'jobTitle': 'Job title',
      'aboutYou': 'About you',
      'cvTypeTemplate': 'CV type & template',
      'cvType': 'CV type',
      'template': 'Template',
      'professionalCv': 'Professional CV',
      'gulfCv': 'Gulf CV',
      'modernTemplate': 'Modern Template',
      'classicTemplate': 'Classic Template',
      'profilePhoto': 'Profile photo',
      'photoPrivacy': 'Photo stays on your device only.',
      'pickImage': 'Pick image',
      'skillsHighlights': 'Skills & highlights',
      'skills': 'Skills',
      'certifications': 'Certifications',
      'courses': 'Courses',
      'awards': 'Achievements',
      'references': 'References',
      'experience': 'Experience',
      'education': 'Education',
      'languages': 'Languages',
      'saveCv': 'Save CV',
      'saving': 'Saving...',
      'chooseTemplate': 'Choose template',
      'addItem': 'Add item',
      'sharePdf': 'Share PDF',
      'shareFail': 'Unable to share PDF right now.',
      'exportFail': 'Unable to export PDF right now.',
      'profile': 'Profile',
      'contact': 'Contact',
      'workExperience': 'Work Experience',
      'summary': 'Summary',
      'namePlaceholder': 'Your Name',
      'jobPlaceholder': 'Job Title',
      'emailPlaceholder': 'email@domain.com',
      'hintsGulfPhoto': 'Photo recommended.',
      'hintsGulfPassport': 'Use passport details.',
      'hintsGulfLicenses': 'List licenses.',
      'hintsProPhoto': 'Photo optional.',
      'hintsProResults': 'Use measurable results.',
      'hintsProSummary': 'Keep summary concise.',
      'myCvs': 'My CVs',
      'myCv': 'My CV',
      'createNewCv': 'Create New CV',
      'noCvsYet': 'No CVs yet',
      'createFirstCv': 'Create your first CV to get started',
      'active': 'Active',
      'setAsActive': 'Set as Active',
      'deleteCv': 'Delete CV',
      'deleteCvConfirm': 'Are you sure you want to delete this CV?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'cvTitle': 'CV Title',
      'cvTitleHint': 'e.g. Developer CV, Marketing CV',
      'cvLanguage': 'Language',
      'noItemsYet': 'No items yet',
      'enterItem': 'Enter item',
      'add': 'Add',
      'cvSaved': 'CV saved successfully',
      'guest': 'Guest',
      'myCvsHint': 'Tap on a CV to make it active and edit it from Dashboard',
      'createFirstCvHint': 'Go to My CVs tab to create your first CV',
      'goToMyCvs': 'Go to My CVs tab',
      'cvCreated': 'CV created successfully',
      'isNowActive': 'is now active',
      'cantDeleteActive':
          'Cannot delete the active CV. Activate another CV first.',
      'cantDeleteLastCv': 'Cannot delete the last CV. Create another CV first.',
      'tapToActivate': 'Tap to activate',
      'create': 'Create',
    },
    'ar': {
      'welcomeBack': 'اهلا بعودتك',
      'signInSubtitle': 'سجّل الدخول لمتابعة بناء سيرتك الرقمية.',
      'loginFailed': 'فشل تسجيل الدخول. تحقق من البيانات.',
      'invalidEmail': 'ادخل بريد الكتروني صحيح.',
      'userNotFound': 'لا يوجد حساب بهذا البريد.',
      'wrongPassword': 'كلمة المرور غير صحيحة.',
      'userDisabled': 'تم تعطيل هذا الحساب.',
      'operationNotAllowed': 'تم تعطيل تسجيل الدخول بالبريد وكلمة المرور.',
      'tooManyRequests': 'محاولات كثيرة. حاول لاحقا.',
      'email': 'البريد الالكتروني',
      'password': 'كلمة المرور',
      'rememberMe': 'تذكرني',
      'rememberMeHint': 'ابقني مسجلا على هذا الجهاز.',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'signIn': 'تسجيل الدخول',
      'signingIn': 'جاري تسجيل الدخول...',
      'googleConnecting': 'جاري الاتصال بجوجل...',
      'continueWithGoogle': 'المتابعة باستخدام جوجل',
      'googleCanceled': 'تم الغاء تسجيل الدخول بجوجل.',
      'googleFailed': 'فشل تسجيل الدخول بجوجل. حاول مرة اخرى.',
      'googleShaHint':
          'فشل تسجيل الدخول بجوجل. اضف SHA-1/256 في فايربيز وحاول مرة اخرى.',
      'networkError': 'خطا في الشبكة. تحقق من الاتصال وحاول مرة اخرى.',
      'newToDigitalCv': 'جديد على السيرة الرقمية؟',
      'createAccount': 'انشاء حساب',
      'creatingAccount': 'جاري انشاء الحساب...',
      'createAccountTitle': 'انشئ حسابك',
      'createAccountSubtitle': 'ابن سيرة احترافية خلال دقائق.',
      'fullName': 'الاسم الكامل',
      'registrationFailed': 'فشل التسجيل. جرّب بريد اخر.',
      'useAtLeast6': 'استخدم 6 احرف على الاقل.',
      'nameRequired': 'الاسم مطلوب.',
      'emailRequired': 'البريد مطلوب.',
      'passwordRequired': 'كلمة المرور مطلوبة.',
      'resetPasswordTitle': 'اعادة تعيين كلمة المرور',
      'resetPasswordSubtitle': 'سنرسل لك رابط اعادة تعيين امن.',
      'resetLinkSent': 'تم ارسال رابط التعيين. تحقق من البريد.',
      'resetFailed': 'تعذر ارسال الرابط. حاول لاحقا.',
      'sendResetLink': 'ارسال رابط التعيين',
      'sending': 'جاري الارسال...',
      'editCv': 'تعديل السيرة',
      'editCvSubtitle': 'حدّث بياناتك واقسامك',
      'previewCv': 'معاينة السيرة',
      'previewCvSubtitle': 'عرض القالب الحالي',
      'changeTemplate': 'تغيير القالب',
      'changeTemplateSubtitle': 'حديث او كلاسيكي',
      'exportPdf': 'تصدير PDF',
      'exportPdfSubtitle': 'انشاء ملف PDF احترافي',
      'logout': 'تسجيل الخروج',
      'logoutSubtitle': 'الخروج من الحساب',
      'dashboard': 'لوحة التحكم',
      'cvCompletion': 'اكتمال السيرة',
      'actions': 'الاجراءات',
      'settings': 'الاعدادات',
      'theme': 'الثيم',
      'darkModeNote': 'الوضع الداكن مفعل افتراضيا لمظهر احترافي.',
      'profileDetails': 'تفاصيل الملف',
      'phoneNumber': 'رقم الهاتف',
      'locations': 'المواقع',
      'jobTitle': 'المسمى الوظيفي',
      'aboutYou': 'نبذة عنك',
      'cvTypeTemplate': 'نوع السيرة والقالب',
      'cvType': 'نوع السيرة',
      'template': 'القالب',
      'professionalCv': 'سيرة احترافية',
      'gulfCv': 'سيرة خليجية',
      'modernTemplate': 'قالب حديث',
      'classicTemplate': 'قالب كلاسيكي',
      'profilePhoto': 'الصورة الشخصية',
      'photoPrivacy': 'الصورة تبقى على جهازك فقط.',
      'pickImage': 'اختيار صورة',
      'skillsHighlights': 'المهارات والابرز',
      'skills': 'المهارات',
      'certifications': 'الشهادات',
      'courses': 'الدورات',
      'awards': 'الإنجازات',
      'references': 'المراجع',
      'experience': 'الخبرات',
      'education': 'التعليم',
      'languages': 'اللغات',
      'saveCv': 'حفظ السيرة',
      'saving': 'جاري الحفظ...',
      'chooseTemplate': 'اختيار القالب',
      'addItem': 'اضافة عنصر',
      'sharePdf': 'مشاركة PDF',
      'shareFail': 'تعذر مشاركة PDF حاليا.',
      'exportFail': 'تعذر تصدير PDF حاليا.',
      'profile': 'الملف',
      'contact': 'بيانات التواصل',
      'workExperience': 'الخبرات العملية',
      'summary': 'الملخص',
      'namePlaceholder': 'اسمك',
      'jobPlaceholder': 'المسمى الوظيفي',
      'emailPlaceholder': 'email@domain.com',
      'hintsGulfPhoto': 'الصورة مستحسنة.',
      'hintsGulfPassport': 'اكتب بيانات الجواز.',
      'hintsGulfLicenses': 'اذكر التراخيص.',
      'hintsProPhoto': 'الصورة اختيارية.',
      'hintsProResults': 'اذكر نتائج قابلة للقياس.',
      'hintsProSummary': 'اختصر الملخص.',
      'myCvs': 'سيراتي الذاتية',
      'myCv': 'سيرتي',
      'createNewCv': 'انشاء سيرة جديدة',
      'noCvsYet': 'لا توجد سير ذاتية',
      'createFirstCv': 'انشئ سيرتك الاولى للبدء',
      'active': 'مفعّلة',
      'setAsActive': 'تعيين كمفعّلة',
      'deleteCv': 'حذف السيرة',
      'deleteCvConfirm': 'هل انت متأكد من حذف هذه السيرة؟',
      'cancel': 'الغاء',
      'delete': 'حذف',
      'cvTitle': 'عنوان السيرة',
      'cvTitleHint': 'مثال: سيرة المطور، سيرة التسويق',
      'cvLanguage': 'اللغة',
      'noItemsYet': 'لا توجد عناصر',
      'enterItem': 'ادخل العنصر',
      'add': 'اضافة',
      'cvSaved': 'تم حفظ السيرة بنجاح',
      'guest': 'ضيف',
      'myCvsHint': 'اضغط على سيرة لتفعيلها ثم عدّلها من لوحة التحكم',
      'createFirstCvHint': 'اذهب لتبويب سيراتي لإنشاء سيرتك الأولى',
      'goToMyCvs': 'اذهب لتبويب سيراتي',
      'cvCreated': 'تم إنشاء السيرة بنجاح',
      'isNowActive': 'أصبحت مفعّلة الآن',
      'cantDeleteActive': 'لا يمكن حذف السيرة المفعّلة. فعّل سيرة أخرى أولاً.',
      'cantDeleteLastCv': 'لا يمكن حذف السيرة الوحيدة. أنشئ سيرة أخرى أولاً.',
      'tapToActivate': 'اضغط للتفعيل',
      'create': 'إنشاء',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
